### ISSUE TITLE
Error Preventing Startup

### ISSUE THREAD

**Issue by Elxafil** [Plugineers/Advanced-Portals#138]
Bungeecord Version: BungeeCord-Bootstrap:1.13-SNAPSHOT:a12bb4c:1388

Startup Error:
`06:05:23 [WARNING] Error enabling plugin AdvancedPortals
java.lang.NoClassDefFoundError: org/bukkit/plugin/java/JavaPlugin
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(Unknown Source)
	at java.base/java.security.SecureClassLoader.defineClass(Unknown Source)
	at java.base/java.net.URLClassLoader.defineClass(Unknown Source)
	at java.base/java.net.URLClassLoader.access$100(Unknown Source)
	at java.base/java.net.URLClassLoader$1.run(Unknown Source)
	at java.base/java.net.URLClassLoader$1.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.net.URLClassLoader.findClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0(PluginClassloader.java:34)
	at net.md_5.bungee.api.plugin.PluginClassloader.loadClass(PluginClassloader.java:27)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at net.md_5.bungee.api.plugin.PluginManager.enablePlugin(PluginManager.java:303)
	at net.md_5.bungee.api.plugin.PluginManager.loadPlugins(PluginManager.java:211)
	at net.md_5.bungee.BungeeCord.start(BungeeCord.java:266)
	at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:56)
	at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
Caused by: java.lang.ClassNotFoundException: org.bukkit.plugin.java.JavaPlugin
	at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0(PluginClassloader.java:53)
	at net.md_5.bungee.api.plugin.PluginClassloader.loadClass(PluginClassloader.java:27)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	... 18 more`

**Comment by sekwah41** [comment]
You don't put it in the bungee folder it's not a bungee mod.
